name: Deploy to UAT Environment

on:
  push:
    branches: [ uat ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: uat
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Deploy to UAT server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.UAT_HOST }}
          username: ${{ secrets.UAT_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/crane
            git fetch origin
            git checkout uat
            git pull origin uat
            docker compose -f docker-compose.uat.yml -p crane-uat build --no-cache
            docker compose -f docker-compose.uat.yml -p crane-uat up -d
            docker compose -f docker-compose.uat.yml -p crane-uat ps

